insert into quotes values(1,1,'Hofstadter''s Law',' It always takes longer than you expect, even when you take Hofstadter''s Law into account.');
insert into quotes values(2,2,'Noelie Altito','The shortest distance between two points is under construction.');
insert into quotes values(3,3,'Scott''s Law','Adding manpower to a late software project makes it later');
insert into quotes values(4,2,'Shaw''s Principle','Build a system that even a fool can use, and only a fool will want to use it.');
insert into quotes values(5,4,'Adolf Hiltler','The great mass of the people  will more easily fall victims to a big lie than a small one');
insert into quotes values(6,5,'G. B. Shaw','There is no satisfaction in hanging a man who does not object to it');
insert into quotes values(7,1,'Heller''s Law','The first myth of management is that it exists');
insert into quotes values(8,3,null,'There are two ways to write error-free programs.  Only the third one works.');
insert into quotes values(9,2,'Fingle''s Creed','Science is true.  Don''t be misled by facts.');
insert into quotes values(10,1,null,'Today is the tomorrow you worried about yesterday');
insert into quotes values(11,1,null,'Love at first sight is one of the greatest labour-saving devices the world has ever seen');
insert into quotes values(12,5,'Oscar Wilde','The only way to get rid of a temptation is to yield to it.');
insert into quotes values(13,5,'Oscar Wilde','There is only one thing in the world worse than being talked about, and that is not being talked about');
insert into quotes values(14,4,'Albert Einstein','I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones.');
insert into quotes values(15,1,'Van Roy''s Law','Love at first sight is one of the greatest labour-saving devices the world has ever seen');
insert into quotes values(16,1,'Groucho Marx','Military justice is to justice what military music is to music');
insert into quotes values(17,3,null,'Old programmers never die.  They just branch to a new address');
insert into quotes values(18,3,'Bradley''s Bromide','If computers get too powerful, we can organize them into a committee -- that will do them in.');
insert into quotes values(19,2,'Carl Zwanzig','Duct tape is like the force.  It has a light side, and a dark side, and it holds the universe together...');
insert into quotes values(20,3,null,'Make it possible for programmers to write in English and you will find the programmers cannot write in English.');
insert into quotes values(21,5,'Joseph Heller','He knew everything there was to know about literature, except how to enjoy it.');
insert into quotes values(22,1,'Evelyn Beatrice Hall','I disapprove of what you say, but I will defend to the death your right to say it');
insert into quotes values(23,5,'Oscar Wilde','I am not at all cynical, I have merely got experience, which, however, is very much the same thing');
insert into quotes values(24,5,'Oscar Wilde','To love oneself is the beginning of a lifelong romance');
insert into quotes values(25,5,'Oscar Wilde','We are all in the gutter, but some of us are looking at the stars');
insert into quotes values(26,5,'Oscar Wilde','London society is full of women of the very highest birth who have, of their own free choice, remained thirty-five for years');
insert into quotes values(27,5,'Lewis Carroll','"Tut, tut, child!"  said the Duchess, "Everything''s got a moral, if only you can find it." ');
insert into quotes values(28,5,'Lewis Carroll','"The time as come" the Walrus said, "to talk of many things"');
insert into quotes values(29,5,'Lewis Carroll','"When I use a word", Humpty Dumpty said, "it means just what I choose it to mean-neither more nor less."');
insert into quotes values(30,1,'Alexander Dumas Snr.','All generalizations are dangerous, including this one');
insert into quotes values(31,2,'Albert Einstein','The true sign of intelligence is not knowledge but imagination');
insert into quotes values(32,6,'Aristophanes','You cannot teach a crab to walk straight');
insert into quotes values(33,6,'Scocrates','True knowledge exists in knowing that you know nothing');
insert into quotes values(34,6,'Euripides','Whom, the Gods would destroy, they first make mad');
insert into quotes values(35,4,'Benjamin Disraeli','The world is wearied of statesmen; whom democracy has degraded into politicians');
insert into quotes values(36,2,'Thomas Huxley','The great tragedy of science:  The slaying of a beautiful theory by an ugly fact');
insert into categories(3,'Computing');
insert into categories(5,'Books & Plays');
insert into categories(6,'Classics');
insert into categories(2,'Science');
insert into categories(4,'Politics');
insert into categories(1,'Words of Wisdom');
