 db.quotes.insert({category:"Words of Wisdom",author:"Hofstadter's Law",quote:" It always takes longer than you expect, even when you take Hofstadter's Law into account"})
 db.quotes.insert({category:"Science",author:"Noelie Altito",quote:"The shortest distance between two points is under construction"})
 db.quotes.insert({category:"Computing",author:"Scott's Lawi",quote:"Adding manpower to a late software project makes it later"})
 db.quotes.insert({category:"Science",author:"Shaw's Principle",quote:"Build a system that even a fool can use, and only a fool will want to use it"})
 db.quotes.insert({category:"Politics",author:"Adolf Hiltler",quote:"The great mass of the people  will more easily fall victims to a big lie than a small one"})
 db.quotes.insert({category:"Books & Plays",author:"G. B. Shaw",quote:"There is no satisfaction in hanging a man who does not object to it"})
 db.quotes.insert({category:"Words of Wisdom",author:"Heller's Law",quote:"The first myth of management is that it exists"})
 db.quotes.insert({category:"Computing",quote:"There are two ways to write error-free programs.  Only the third one works"})
 db.quotes.insert({category:"Science",author:"Fingle's Creed",quote:"Science is true.  Don't be misled by facts"})
 db.quotes.insert({category:"Words of Wisdom",quote:"Today is the tomorrow you worried about yesterday"})

 db.quotes.insert({category:"Words of Wisdom:",quote:"Love at first sight is one of the greatest labour-saving devices the world has ever seen"})
 db.quotes.insert({category:"Books & Plays",author:"Oscar Wilde",quote:"The only way to get rid of a temptation is to yield to it."})
 db.quotes.insert({category:"Books & Plays",author:"Oscar Wilde",quote:"There is only one thing in the world worse than being talked about, and that is not being talked about"})
 db.quotes.insert({category:"Politics",author:"Albert Einstein",quote:"I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones."})
 db.quotes.insert({category:"Words of Wisdom",author:"Van Roy's Law",quote:"Love at first sight is one of the greatest labour-saving devices the world has ever seen"})
 db.quotes.insert({category:"Words of Wisdom",author:"Groucho Marx",quote:"Military justice is to justice what military music is to music"})
 db.quotes.insert({category:"Computing",quote:"Old programmers never die. They just branch to a new address"})
 db.quotes.insert({category:"Computing",author:"Bradley's Bromide",quote:"If computers get too powerful, we can organize them into a committee -- that will do them in."})
 db.quotes.insert({category:"Science",author:"Carl Zwanzig",quote:"Duct tape is like the force.  It has a light side, and a dark side, and it holds the universe together..."})
 db.quotes.insert({category:"Computing",quote:"Make it possible for programmers to write in English and you will find the programmers cannot write in English."})

 db.quotes.insert({category:"Books & Plays",author:"Joseph Heller",quote:"He knew everything there was to know about literature, except how to enjoy it."})
 db.quotes.insert({category:"Words of Wisdom",author:"Evelyn Beatrice Hall",quote:"I disapprove of what you say, but I will defend to the death your right to say it"})
 db.quotes.insert({category:"Books & Plays",author:"Oscar Wilde",quote:"I am not at all cynical, I have merely got experience, which, however, is very much the same thing"})
 db.quotes.insert({category:"Books & Plays",author:"Oscar Wilde",quote:"To love oneself is the beginning of a lifelong romance"})
 db.quotes.insert({category:"Books & Plays",author:"Oscar Wilde",quote:"We are all in the gutter, but some of us are looking at the stars"})
 db.quotes.insert({category:"Books & Plays",author:"Oscar Wilde",quote:"London society is full of women of the very highest birth who have, of their own free choice, remained thirty-five for years"})
 db.quotes.insert({category:"Books & Plays",author:"Lewis Carroll",quote:"Tut, tut, child!  said the Duchess, Everything's got a moral, if only you can find it"})
 db.quotes.insert({category:"Books & Plays",author:"Lewis Carroll",quote:"The time as come the Walrus said, to talk of many things"})
 db.quotes.insert({category:"Books & Plays",author:"Lewis Carroll",quote:"When I use a word, Humpty Dumpty said, it means just what I choose it to mean-neither more nor less"})
 db.quotes.insert({category:"Words of Wisdom",author:"Alexander Dumas Snr.",quote:"All generalizations are dangerous, including this one"})

 db.quotes.insert({category:"Science",author:"Albert Einstein",quote:"The true sign of intelligence is not knowledge but imagination"})
 db.quotes.insert({category:"Classics",author:"Aristophanes",quote:"You cannot teach a crab to walk straight"})
 db.quotes.insert({category:"Classics",author:"Scocrates",quote:"True knowledge exists in knowing that you know nothing"})
 db.quotes.insert({category:"Classics",author:"Euripides",quote:"Whom the Gods would destroy, they first make mad"})
 db.quotes.insert({category:"Politics",author:"Benjamin Disraeli",quote:"The world is wearied of statesmen; whom democracy has degraded into politicians"})
 db.quotes.insert({category:"Science",author:"Thomas Huxley",quote:"The great tragedy of science:  The slaying of a beautiful theory by an ugly fact"})
